### PR TITLE
Fix complete inheritance with the wrong type binding

### LINKED ISSUE #11: Inherited methods aren't remapped
```
CL: pr net/minecraft/entity/EntityLivingBase
CL: bew net/minecraft/client/entity/EntityPlayerSP
MD: pr/i (F)V net/minecraft/entity/EntityLivingBase/setHealth (F)V
```
```java
// in mixin targeting EntityPlayerSP
@Inject(
        method = "damageEntity(Lnet/minecraft/util/DamageSource;F)V",
        at = @At(
                value = "INVOKE",
                target = "Lnet/minecraft/client/entity/EntityPlayerSP;setHealth(F)V"
        )
)
```
this isn't being remapped to `Lbew;i(F)V`.

If I switch it to `"Lnet/minecraft/entity/EntityLivingBase;setHealth(F)V"`, it'll be remapped to `Lpr;i(F)V`, but Mixin won't find it when trying to inject.

### PR DESCRIPTION
**Pull request by qouteall**
Without this fix, for example, it will complete inheritance for Entity with type binding of MixinEntity.  After that Entity's mapping will be marked as completed and remapping its inherited method call will fail. Normally Entity's inheritance should be completed by Entity's type binding.

Fixes #11

### CODE REVIEW

File: src/main/java/org/cadixdev/mercury/mixin/MixinRemapperVisitor.java [hunk 1]
```diff
@@ -167,7 +167,10 @@ public boolean visit(final MethodDeclaration node) {
         // todo: support multiple targets properly
         final ClassMapping<?, ?> target = this.mappings.computeClassMapping(mixin.getTargetBinaryName()).orElse(null);
         if (target == null) return true;
-        target.complete(this.inheritanceProvider, declaringClass);
+
+        for (ITypeBinding mixinTarget : mixin.getTargets()) {
```
Comment (jamierocks) [inline src/main/java/org/cadixdev/mercury/mixin/MixinRemapperVisitor.java]: final

File: src/main/java/org/cadixdev/mercury/mixin/MixinRemapperVisitor.java [hunk 2]
```diff
@@ -167,7 +167,10 @@ public boolean visit(final MethodDeclaration node) {
...
+            target.complete(inheritanceProvider, mixinTarget);
```
Comment (jamierocks) [inline src/main/java/org/cadixdev/mercury/mixin/MixinRemapperVisitor.java]: this.inheritanceProvider

**Review by phase — APPROVED** [review]
